services:
  postgres:
    image: public.ecr.aws/docker/library/postgres:16.3
    container_name: renec_postgresql
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Renec2024
      POSTGRES_DB: postgres
